/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ana
 */
public class PromeniPotvrdaForm extends javax.swing.JFrame {

    /**
     * Creates new form AzurirajStavkuRezervacijeForm
     */
    public PromeniPotvrdaForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        klijentCombo1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        potvrdaRezervacijeIdTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        stavkeTable = new javax.swing.JTable();
        obrisiStavkuBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        iznosTxt = new javax.swing.JTextField();
        azurirajBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        uslugaCombo = new javax.swing.JComboBox<>();
        dodajBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Upravljanje potvrdama rezervacije");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Potvrda rezervacije");

        potvrdaRezervacijeIdTxt.setEditable(false);

        stavkeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(stavkeTable);

        obrisiStavkuBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        obrisiStavkuBtn.setText("Obrisi");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ukupan iznos");

        iznosTxt.setEditable(false);

        azurirajBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        azurirajBtn.setText("Azuriraj");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Usluga");

        dodajBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dodajBtn.setText("Dodaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(potvrdaRezervacijeIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iznosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uslugaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(azurirajBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dodajBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(obrisiStavkuBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(potvrdaRezervacijeIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(iznosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uslugaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(dodajBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obrisiStavkuBtn)
                    .addComponent(azurirajBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void obrisiBtnAddActionListener(ActionListener actionListener) {
        obrisiStavkuBtn.addActionListener(actionListener);
    }

    /**
     * @param args the command line arguments
     */
    public JTextField getPotvrdaRezervacijeIdTxt() {
        return potvrdaRezervacijeIdTxt;
    }

    public void setPotvrdaRezervacijeIdTxt(JTextField potvrdaRezervacijeIdTxt) {
        this.potvrdaRezervacijeIdTxt = potvrdaRezervacijeIdTxt;
    }

    public JTable getStavkeTable() {
        return stavkeTable;
    }

    public JButton getObrisiStavkuBtn() {
        return obrisiStavkuBtn;
    }

    public JTextField getIznosTxt() {
        return iznosTxt;
    }

    public void setIznosTxt(JTextField iznosTxt) {
        this.iznosTxt = iznosTxt;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton azurirajBtn;
    private javax.swing.JButton dodajBtn;
    private javax.swing.JTextField iznosTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Object> klijentCombo1;
    private javax.swing.JButton obrisiStavkuBtn;
    private javax.swing.JTextField potvrdaRezervacijeIdTxt;
    private javax.swing.JTable stavkeTable;
    private javax.swing.JComboBox<Object> uslugaCombo;
    // End of variables declaration//GEN-END:variables

    public void azurirajBtnActionListener(ActionListener actionListener) {
        azurirajBtn.addActionListener(actionListener);
    }

    public void dodajBtnActionListener(ActionListener actionListener) {
        dodajBtn.addActionListener(actionListener);
    }

    public JComboBox<Object> getUslugaCombo() {
        return uslugaCombo;
    }

}
