/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ana
 */
public class ServicesViewForm extends javax.swing.JFrame {

    /**
     * Creates new form ServicesViewForm
     */
    public ServicesViewForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sveUslugeTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gornjaGranicaTxt = new javax.swing.JTextField();
        donjaCenaTxt = new javax.swing.JTextField();
        gornjaTrajanjeTxt = new javax.swing.JTextField();
        pretraziBtn = new javax.swing.JButton();
        resetujBtn = new javax.swing.JButton();
        azurirajBtn = new javax.swing.JButton();
        obrisiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usluge");

        sveUslugeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(sveUslugeTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cena");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Trajanje");

        gornjaGranicaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        donjaCenaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        gornjaTrajanjeTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pretraziBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pretraziBtn.setText("Pretrazi");

        resetujBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetujBtn.setText("Resetuj");

        azurirajBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        azurirajBtn.setText("Azuriraj");

        obrisiBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        obrisiBtn.setText("Obrisi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(donjaCenaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gornjaGranicaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gornjaTrajanjeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pretraziBtn)
                            .addComponent(resetujBtn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(azurirajBtn)
                .addGap(18, 18, 18)
                .addComponent(obrisiBtn)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gornjaGranicaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pretraziBtn)
                        .addComponent(donjaCenaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetujBtn)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(gornjaTrajanjeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(azurirajBtn)
                    .addComponent(obrisiBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JTextField getDonjaCenaTxt() {
        return donjaCenaTxt;
    }

    public void setDonjaCenaTxt(JTextField donjaCenaTxt) {
        this.donjaCenaTxt = donjaCenaTxt;
    }

    public JTextField getGornjaGranicaTxt() {
        return gornjaGranicaTxt;
    }

    public void setGornjaGranicaTxt(JTextField gornjaGranicaTxt) {
        this.gornjaGranicaTxt = gornjaGranicaTxt;
    }

    public JTextField getGornjaTrajanjeTxt() {
        return gornjaTrajanjeTxt;
    }

    public void setGornjaTrajanjeTxt(JTextField gornjaTrajanjeTxt) {
        this.gornjaTrajanjeTxt = gornjaTrajanjeTxt;
    }

    public JButton getPretraziBtn() {
        return pretraziBtn;
    }

    public void setPretraziBtn(JButton pretraziBtn) {
        this.pretraziBtn = pretraziBtn;
    }

    public JButton getResetujBtn() {
        return resetujBtn;
    }

    public void setResetujBtn(JButton resetujBtn) {
        this.resetujBtn = resetujBtn;
    }

    public JTable getSveUslugeTable() {
        return sveUslugeTable;
    }

    public void setSveUslugeTable(JTable sveUslugeTable) {
        this.sveUslugeTable = sveUslugeTable;
    }

    public JButton getAzurirajBtn() {
        return azurirajBtn;
    }

    public JButton getObrisiBtn() {
        return obrisiBtn;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton azurirajBtn;
    private javax.swing.JTextField donjaCenaTxt;
    private javax.swing.JTextField gornjaGranicaTxt;
    private javax.swing.JTextField gornjaTrajanjeTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton obrisiBtn;
    private javax.swing.JButton pretraziBtn;
    private javax.swing.JButton resetujBtn;
    private javax.swing.JTable sveUslugeTable;
    // End of variables declaration//GEN-END:variables

    public void pretraziAddActionListener(ActionListener actionListener) {
        pretraziBtn.addActionListener(actionListener);
    }

    public void resetujAddActionListener(ActionListener actionListener) {
        resetujBtn.addActionListener(actionListener);
    }

    public void azurirajAddActionListener(ActionListener actionListener) {
        azurirajBtn.addActionListener(actionListener);
    }

    public void obrisiAddActionListener(ActionListener actionListener) {
        obrisiBtn.addActionListener(actionListener);
    }

}
