/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ana
 */
public class SviKozmeticariForm extends javax.swing.JFrame {

    /**
     * Creates new form SviKozmeticariForm
     */
    public SviKozmeticariForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kozmTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        imePrezimeTxt = new javax.swing.JTextField();
        datumTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sertifikatCombo = new javax.swing.JComboBox<>();
        resetujBtn = new javax.swing.JButton();
        pretraziBtn = new javax.swing.JButton();
        azurirajBtn = new javax.swing.JButton();
        obrisiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kozmeticari");

        kozmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(kozmTable);

        jLabel1.setText("Ime i prezime");

        jLabel2.setText("ID");

        jLabel3.setText("Datum");

        jLabel4.setText("Sertifikat");

        resetujBtn.setText("Resetuj");

        pretraziBtn.setText("Pretrazi");

        azurirajBtn.setText("Azuriraj");

        obrisiBtn.setText("Obrisi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(azurirajBtn)
                        .addGap(18, 18, 18)
                        .addComponent(obrisiBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sertifikatCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datumTxt)
                            .addComponent(imePrezimeTxt)
                            .addComponent(idTxt))
                        .addGap(36, 36, 36)
                        .addComponent(pretraziBtn)
                        .addGap(18, 18, 18)
                        .addComponent(resetujBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(imePrezimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(datumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sertifikatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetujBtn)
                    .addComponent(pretraziBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(azurirajBtn)
                    .addComponent(obrisiBtn))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JButton getAzurirajBtn() {
        return azurirajBtn;
    }

    public void setAzurirajBtn(JButton azurirajBtn) {
        this.azurirajBtn = azurirajBtn;
    }

    public JTextField getDatumTxt() {
        return datumTxt;
    }

    public void setDatumTxt(JTextField datumTxt) {
        this.datumTxt = datumTxt;
    }

    public JTextField getIdTxt() {
        return idTxt;
    }

    public void setIdTxt(JTextField idTxt) {
        this.idTxt = idTxt;
    }

    public JTextField getImePrezimeTxt() {
        return imePrezimeTxt;
    }

    public void setImePrezimeTxt(JTextField imePrezimeTxt) {
        this.imePrezimeTxt = imePrezimeTxt;
    }

    public JTable getKozmTable() {
        return kozmTable;
    }

    public void setKozmTable(JTable kozmTable) {
        this.kozmTable = kozmTable;
    }

    public JButton getObrisiBtn() {
        return obrisiBtn;
    }

    public void setObrisiBtn(JButton obrisiBtn) {
        this.obrisiBtn = obrisiBtn;
    }

    public JButton getPretraziBtn() {
        return pretraziBtn;
    }

    public void setPretraziBtn(JButton pretraziBtn) {
        this.pretraziBtn = pretraziBtn;
    }

    public JButton getResetujBtn() {
        return resetujBtn;
    }

    public void setResetujBtn(JButton resetujBtn) {
        this.resetujBtn = resetujBtn;
    }

    public JComboBox<Object> getSertifikatCombo() {
        return sertifikatCombo;
    }

    /**
     * @param args the command line arguments
     */
    public void setSertifikatCombo(JComboBox<Object> sertifikatCombo) {
        this.sertifikatCombo = sertifikatCombo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton azurirajBtn;
    private javax.swing.JTextField datumTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JTextField imePrezimeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kozmTable;
    private javax.swing.JButton obrisiBtn;
    private javax.swing.JButton pretraziBtn;
    private javax.swing.JButton resetujBtn;
    private javax.swing.JComboBox<Object> sertifikatCombo;
    // End of variables declaration//GEN-END:variables

    public void obrisiAddActionListener(ActionListener actionListener) {
        obrisiBtn.addActionListener(actionListener);
    }
}
