/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import server.Server;

/**
 *
 * @author Ana
 */
public class ServerForm extends javax.swing.JFrame {

    Server server;

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        server = new Server();
        statusTxt.setText("");
        pokreniBtn.setEnabled(true);
        zaustaviBtn.setEnabled(false);
                setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pokreniBtn = new javax.swing.JButton();
        zaustaviBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        statusTxt = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pokreniBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pokreniBtn.setText("POKRENI SERVER");
        pokreniBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokreniBtnActionPerformed(evt);
            }
        });

        zaustaviBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        zaustaviBtn.setText("ZAUSTAVI SERVER");
        zaustaviBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zaustaviBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Status:");

        statusTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusTxt.setText("jLabel2");

        jMenu1.setText("Konfiguracija");

        jMenuItem1.setText("baza");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("port");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zaustaviBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(pokreniBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusTxt)
                .addGap(18, 18, 18)
                .addComponent(pokreniBtn)
                .addGap(18, 18, 18)
                .addComponent(zaustaviBtn)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FormConfigBaza baza = new FormConfigBaza(this, true);
        baza.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormConfigPort port = new FormConfigPort(this, true);
        port.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void pokreniBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokreniBtnActionPerformed
        // TODO add your handling code here:
        server.start();
        statusTxt.setText("POKRENUT");        
        zaustaviBtn.setEnabled(true);
        pokreniBtn.setEnabled(false);
    }//GEN-LAST:event_pokreniBtnActionPerformed

    private void zaustaviBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zaustaviBtnActionPerformed
        // TODO add your handling code here:
        server.zaustaviServer();
        statusTxt.setText("ZAUSTAVLJEN");
        pokreniBtn.setEnabled(true);        
        zaustaviBtn.setEnabled(false);

    }//GEN-LAST:event_zaustaviBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton pokreniBtn;
    private javax.swing.JLabel statusTxt;
    private javax.swing.JButton zaustaviBtn;
    // End of variables declaration//GEN-END:variables
}
